[workspace]
members = [
  "crates/hop",
  "crates/hop-core",
  "crates/hop-protocol",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/serhii-kucherenko/hop"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.98"
chacha20poly1305 = "0.10.1"
clap = { version = "=4.5.20", features = ["derive"] }
hmac = "0.12.1"
hkdf = "0.12.4"
rand = "0.8.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "net", "time", "io-util"] }
bincode = "1.3.3"
zeroize = "=1.8.2"
